pipeline{

    agent any

    environment{
        DOCKER_USER = credentials('docker_user')
        DOCKER_PASS = credentials('docker_pass')
    }


    parameters {
        string defaultValue: '${BUILD_NUMBER}', description: 'Enter the version of the docker image', name: 'VERSION'
        choice choices: ['true', 'false'], description: 'Skip test', name: 'TEST'
    }

    stages{
     
        stage("Build java app"){
            steps{
                sh "mvn clean package install"
                
            }
        }
        stage("Test java app"){
            steps{
                // sh "mvn test"
                sh "mvn test -Dmaven.test.skip=${TEST}"
                
            }
        }
        stage("build java app image"){
            steps{
                sh "docker build -t mariam191/java_app:V${VERSION} . "
            }
        }

        stage("push java app image"){
            steps{
                sh "docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}"
                sh "docker push mariam191/java_app:V${VERSION}"
            }
        }

    }

    post{
        always{
            sh "echo 'Clean the Workspace'"
            cleanWs()
        }
        failure {
            sh "echo 'failed'"
        }
    }
}
