pipeline{

    agent any
    
    environment{
        DOCKER_USER = credentials('docker_user')
        DOCKER_PASS = credentials('docker_pass')
    }
    stages{
     
        stage("Build java app"){
            steps{
                sh "mvn clean package install"
                
            }
        }
        stage("Test java app"){
            steps{
                sh "mvn test"
                
            }
        }
        stage("build java app image"){
            steps{
                sh "docker build -t mariam191/java_app:V${BUILD_NUMBER} . "
            }
        }

        stage("push java app image"){
            steps{
                sh "docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}"
                sh "docker push mariam191/java_app:V${BUILD_NUMBER}"
            }
        }

    }

    post{
        always{
            sh "echo 'Clean the Workspace'"
            cleanWs()
        }
        failure {
            sh "echo 'failed'"
        }
    }
}
